Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Circuit breaker tripped. Stopped predicting more actions for sender 'default'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "Barkat Khan"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "9556462310"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Failed to run custom action 'action_default_fallback'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1f09be48>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faf1f09be48>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1f09be48>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 327, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/utils.py", line 748, in request
    **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf1f09be48>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 348, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/envs/new_env/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:89: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/tarun.bhavnani@dev.smecorner.com/anaconda3/envs/new_env/lib/python3.6/site-packages/sklearn/base.py:253: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.20.2 when using version 0.20.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/envs/new_env/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/tarun.bhavnani@dev.smecorner.com/anaconda3/envs/new_env/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.20.2 when using version 0.19.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/envs/new_env/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "Sir"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Failed to run custom action 'action_default_fallback'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b4501b320>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0b4501b320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b4501b320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 327, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/utils.py", line 748, in request
    **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b4501b320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 348, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "Sir"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "Sir"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani\\"}' after the action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Circuit breaker tripped. Stopped predicting more actions for sender 'default'
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "7838930304"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhav"}' after the action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Failed to run custom action 'action_business_years_explain'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_business_years_explain'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 338, in run
    response.raise_for_status()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 358, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Circuit breaker tripped. Stopped predicting more actions for sender 'default'
Action 'action_fetch_details' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "Sir"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhav"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarn b"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_default_fallback'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90c6bd1630>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f90c6bd1630>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90c6bd1630>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 327, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/utils.py", line 748, in request
    **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90c6bd1630>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 348, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "it is fun"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Failed to run custom action 'action_default_fallback'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3071e39e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa3071e39e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3071e39e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 327, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/utils.py", line 748, in request
    **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3071e39e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/processor.py", line 351, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_core/actions/action.py", line 348, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "no man its not possible"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bha"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun"}' after the action.
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bh"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun"}' after the action.
Rasa process starting
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/latest_nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

Restoring parameters from models/nlu/default/latest_nlu/intent_classifier_tensorflow_embedding.ckpt
/home/tarun.bhavnani@dev.smecorner.com/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Action 'action_fetch_details' set a slot type 'user_cell' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_cell": "12345"}' after the action.
Action 'action_default_fallback' set a slot type 'user_name' that it never set during the training. This can throw of the prediction. Make sure to include training examples in your stories for the different types of slots this action can return. Remember: you need to set the slots manually in the stories by adding '- slot{"user_name": "tarun bhavnani"}' after the action.
